### ISSUE TITLE
Terms of Service Link Missing in LMS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#126]
The MITx TOS link should be at the bottom of the page on https://mitx-qa-next.mitx.mit.edu/dashboard below the Open edX link, as they are currently on LMS and the link should take the user to https://lms.mitx.mit.edu/tos. The TOS link does show up on https://studio-mitx-qa-next.mitx.mit.edu

Current LMS:
<img width="1538" alt="Screen Shot 2020-12-02 at 9 50 04 PM" src="https://github.mit.edu/storage/user/9183/files/f573dc00-34e8-11eb-9690-d1bd11078835">
https://lms.mitx.mit.edu/dashboard

mitx-qa-next: 
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/430126/101087786-c1e49080-3580-11eb-9b8f-0f644a638324.png">

**Comment by HamzaIbnFarooq** [comment]
@pdpinch I have tried to regenerate this issue locally, but I am unable to achieve that. I do not have access to https://mitx-qa-next.mitx.mit.edu/dashboard can you please create an account for me?

**Comment by asadiqbal08** [comment]
I am looking over this issue and it seems me `footer.html` is not applying from edx themes repository but utliiziing the default one from `LMS`, Investigating it yet

**Comment by asadiqbal08** [comment]
@HamzaIbnFarooq  @pdpinch , I looked over it again today. I verified that my themes are working fine and I verified that `terms-of-service` link area's code is already implemented in our theme repo's  [footer](https://github.com/mitodl/mitx-theme/blob/master/lms/templates/footer.html#L30-L32) but the issue is that, edX devstack is not loading the footer contents from themes directory but applying the default one from `edx-platform/lms/templates/footer.html`

Anyone know, Does the footer area not support for theming by openEdx ? I can see something similar in LMS [API branding side](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/branding/api.py#L40-L46) where trying to get footer contents e.g. `legal_links`, `navigation_links` etc etc.

**Comment by pdpinch** [comment]
@asadiqbal08 which page(s) are you testing on? I think different templates may load the footer from different locations.

**Comment by pdpinch** [comment]
I'm also puzzled why this seems to be working OK in xPRO but not Residential MITx. Do they set the TOS link in different ways?

**Comment by HamzaIbnFarooq** [comment]
According to my observations, a variable named `MKTG_URL_LINK_MAP` present in `lms.env.json` is responsible for this issue. `MKTG_URL_LINK_MAP` is a dict having Marketing URLs in it.

If `MKTG_URL_LINK_MAP` has `TOS_AND_HONOR` URL in it then edX will not render separate `TOS` and `HONOR` URLs ([reference](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/branding/api.py#L316-L323)). And this is exactly what's happening with Residential MITx because our theme is dependent on `TOS` URL.

A possible solution is to assign `#` to `TOS_AND_HONOR`, in `lms.env.json`.

cc: @pdpinch @asadiqbal08 @blarghmatey

**Comment by pdpinch** [comment]
How do we handle this in xPRO? Is it different?

**Comment by HamzaIbnFarooq** [comment]
In xPro, TOS_AND_HONOR link seems to be already removed (maybe via direct changes in edx-platform)

**Comment by blarghmatey** [comment]
I added that value to the link map for residential and it appears to have resolved the issue.
